version: '3.3'
services:
  fileserver:
    image: arm64v8/python 
    restart: always
    ports:
      - '4858:4858'
    volumes:
      -  ./:/hostfiles
    command: sh -c "cd /hostfiles && python3 -m http.server 4858"
  memgraph-platform:
      ports:
          - '7687:7687'
          - '7444:7444'
          - '3000:3000'
      image: memgraph/memgraph-platform